CREATE EXTENSION IF NOT EXISTS vector;
CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS documents;
CREATE SCHEMA IF NOT EXISTS conversations;
GRANT ALL PRIVILEGES ON SCHEMA auth TO finsight;
GRANT ALL PRIVILEGES ON SCHEMA documents TO finsight;
GRANT ALL PRIVILEGES ON SCHEMA conversations TO finsight;